alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~/'
alias ls='ls -a'
alias g='git'
alias vim='nvim'
alias vi='nvim'
alias vimdiff='nvim -d'

git() {
  if [ "$1" = commit ]; then
    shift
    set -- commit -S "$@"
  fi
  command git "$@"
}
